on: [push, pull_request]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        job_name: ['linux', 'windows', 'macos']

        include:
        - job_name: linux
          os: ubuntu-latest
          shell: bash {0}

        - job_name: windows
          os: windows-latest
          shell: msys2 {0}

        - job_name: macos
          os: macos-latest
          shell: bash {0}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    name: fixGB-${{ matrix.job_name }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: msys2/setup-msys2@v2
      if: matrix.os == 'windows-latest'
      with:
        path-type: inherit
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-openal mingw-w64-x86_64-freeglut mingw-w64-x86_64-minizip2
    
    - run: sudo apt install -y libopenal-dev libopengl-dev freeglut3-dev libgtk-3-dev libminizip-dev
      if: matrix.os == 'ubuntu-latest'
    
    - run: brew install openal-soft freeglut minizip xquartz
      if: matrix.os == 'macos-latest'

    - uses: actions/checkout@v1
      with:
        submodules: true

    - run: make -j$(nproc)
      env:
        FILESELECT: 1
        ZIPSUPPORT: 1

    - uses: actions/upload-artifact@v2
      with:
        name: fixGB-${{ matrix.job_name }}
        path: fixGB*
